--[=[

		██     ██ ██ ██████  
		██     ██ ██ ██   ██ 
		██  █  ██ ██ ██████  
		██ ███ ██ ██ ██      
		 ███ ███  ██ ██      
                    
	  THIS IS WORK IN PROGRESS

--]=]

-- visuals section. esp tab, colors tab. each component is groupbox. esp tab is whats enabled, colors is colors and transparency
-- if games is arsenal, auto set health to nrpbs

--// This is Assuming You Already Have Imported/Defined The Library, With it being named Twilight.
--// We will be using Starlight Interface Suite to help visualise all the toggles for the user. https://nebulasoftworks.xyz/starlight
-- local Starlight = loadstring(game:HttpGet("https://raw.nebulasoftworks.xyz/starlight"))()
-- local NebulaIcons = loadstring(game:HttpGet("https://raw.nebulasoftworks.xyz/nebula-icon-library-loader"))()

-- local Window = Starlight:CreateWindow({
-- 	Name = "Twilight ESP",
-- 	Subtitle = "Example Script",
-- 	Icon = NebulaIcons:GetIcon("view_in_ar"),

-- 	LoadingEnabled = false,
-- 	LoadingSettings = {
-- 		Title = "twilight esp",
-- 		Subtitle = "twilight esp",
-- 	},

-- 	FileSettings = {
-- 		ConfigFolder = "TwilightESPExample",
-- 	},
-- })
-- local TabSection = Window:CreateTabSection("Visuals")
-- local _Tabs = {
-- 	ESP = TabSection:CreateTab({
-- 		Name = "ESPs",
-- 		Icon = NebulaIcons:GetIcon("eye_tracking"),
-- 		Columns = 2,
-- 	}, "INDEX"),
-- 	Colors = TabSection:CreateTab({
-- 		Name = "Colors",
-- 		Icon = NebulaIcons:GetIcon("palette", "Symbols-Filled"),
-- 		Columns = 2,
-- 	}, "INDEX"),
-- }
